#!/bin/bash

# todo make a theme .rasi for each menu

green=$(xrdb -query | grep "color2" | head -n1 | awk '{print $NF}')
blue=$(xrdb -query | grep "color4" | head -n1 | awk '{print $NF}')

calendar=$(~/.config/polybar/modules/calendar $green $blue)

echo "$calendar" | rofi -dmenu -theme calendarmenu -markup-rows -scroll-method 0 > /dev/null

if [ "$#" -eq 1 ]; then
    kill -USR1 $1
fi
