#!/usr/bin/env python
# encoding:utf8

import calendar
import datetime
import locale
import sys


def rofiFormatMonth(month_str, month, year, month_str_color, day_active_color, today=None):
    """
    Format a month for rofi
    month_str is the calendar of the month
    month is the number of the month
    today is the date used to highlight the current day
    """
    month_lines = month_str.splitlines()
    if today is not None and today.month == month and today.year == year:
        month_lines[0] = today.strftime(
            "%a %d %b %Y").center(len(month_lines[1]), ' ')
        for i in range(len(month_lines[2:])):
            index = month_lines[2 + i].find(str(today.day))
            if index > -1:
                month_lines[2 + i] = month_lines[2 + i][:index] + \
                    '<b><u><span foreground="' + day_active_color + '">' + str(today.day) + \
                    '</span></u></b>' + month_lines[2 +
                                                    i][index + len(str(today.day)):]
                break

    # month name
    month_lines[0] = '<span color="' + month_str_color + \
        '">' + month_lines[0] + '</span>'
    # day names
    month_lines[1] = '<b>' + month_lines[1] + '</b>'

    print('\n'.join(month_lines))
    if (len(month_lines) < 8):
        print()


if __name__ == "__main__":
    locale.setlocale(locale.LC_ALL, '')
    tcal = calendar.TextCalendar()
    today = datetime.date.today()

    month_str_color = "green"
    day_active_color = "blue"
    if len(sys.argv) > 2:
        month_str_color = sys.argv[1]
        day_active_color = sys.argv[2]

    count = 0
    for m in range(today.month, 13):
        month = tcal.formatmonth(today.year, m)
        rofiFormatMonth(month, m, today.year, month_str_color,
                        day_active_color, today)
        count += 1

    for m in range(1, 13 - count):
        month = tcal.formatmonth(today.year + 1, m)
        rofiFormatMonth(month, m, today.year + 1,
                        month_str_color, day_active_color, today)
