#! /bin/sh

bspc monitor -d I II III IV V VI 

bspc config border_width         2
bspc config window_gap          12

#=========================================================

# colors
red=$(xrdb -query | grep "color1" | head -n1 | awk '{print $NF}')
red_alt=$(xrdb -query | grep "color9" | head -n1 | awk '{print $NF}')
green=$(xrdb -query | grep "color2" | head -n1 | awk '{print $NF}')
green_alt=$(xrdb -query | grep "color10" | head -n1 | awk '{print $NF}')
yellow=$(xrdb -query | grep "color3" | head -n1 | awk '{print $NF}')
yellow_alt=$(xrdb -query | grep "color11" | head -n1 | awk '{print $NF}')
blue=$(xrdb -query | grep "color4" | head -n1 | awk '{print $NF}')
blue_alt=$(xrdb -query | grep "color12" | head -n1 | awk '{print $NF}')
black_alt=$(xrdb -query | grep "color8" | head -n1 | awk '{print $NF}')
black=$(xrdb -query | grep "color0" | head -n1 | awk '{print $NF}')

bspc config active_border_color $red_alt
bspc config normal_border_color $black_alt
bspc config focused_border_color $red
bspc config presel_feedback_color $yellow

#=========================================================

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config single_monocle       true

# Firefox's main window
bspc rule -a Firefox:Navigator desktop='^2' state=tiling
# The child windows
bspc rule -a Firefox:Browser state=floating center=true
bspc rule -a Firefox:Places state=floating center=true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating follow=on

# contains rules for vscode
bspc config external_rules_command ~/.config/bspwm/external_rules

~/.fehbg
compton &
redshift -c ~/.config/redshift.conf &
$HOME/.config/polybar/launch.sh
